In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np
import pickle

# Person Detection

In [2]:
data = pd.read_csv('combined_train_speakers.csv')
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scalar = StandardScaler()
X_train_scaled = scalar.fit_transform(X_train)
X_test_scaled = scalar.transform(X_test)

#svm

svm = SVC(kernel='rbf', C=1)
svm.fit(X_train_scaled, y_train)

y_pred = svm.predict(X_test_scaled)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


0.9543080939947781
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       537
           1       0.96      0.89      0.92      1037
           2       0.93      0.94      0.94       651
           3       0.90      0.95      0.92       959
           4       1.00      1.00      1.00       893
           5       0.95      0.95      0.95       532
           6       0.97      0.99      0.98      1137
           7       0.95      0.93      0.94       382

    accuracy                           0.95      6128
   macro avg       0.95      0.95      0.95      6128
weighted avg       0.95      0.95      0.95      6128

[[ 528    0    2    2    0    2    0    3]
 [   0  920    3   80    2    6   25    1]
 [   4    5  612   19    0    6    2    3]
 [   4   20   17  908    1    2    3    4]
 [   0    0    1    0  892    0    0    0]
 [   1   13   10    1    0  503    0    4]
 [   2    0    0    2    0    2 1129    2]
 [   2    0   12    2    0   

In [4]:
X_new = pd.read_csv('recorded_audio.csv')
X_new_scaled = scalar.transform(X_new)  # Use the same scaler from training

y_new_pred = svm.predict(X_new_scaled)  # Use the trained model (best_svm)
print("Predictions on new data:", y_new_pred)
print("Output mode of the array:", np.bincount(y_new_pred).argmax())

Predictions on new data: [0 0 5 7 7 7 0 0 0 0 7 7 7 7 7 7 7 7 7 7 7 7 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0
 0 0 3 3 3 3 0 0 0 3 3 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 7 7 0 0 0 7
 7 7 7 7 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Output mode of the array: 0


In [7]:
pickle.dump(svm, open('person_detection_model.pkl', 'wb'))

In [8]:
person_detection_loader = pickle.load(open('person_detection_model.pkl', 'rb'))

In [9]:
y = person_detection_loader.predict(X_new_scaled)
percentage_distribution = np.bincount(y) / len(y) * 100

# Print percentage distribution
print("Percentage distribution of predictions:")
for class_label, percentage in enumerate(percentage_distribution):
    print(f"Class {class_label}: {percentage:.2f}%")

Percentage distribution of predictions:
Class 0: 66.67%
Class 1: 0.00%
Class 2: 0.00%
Class 3: 8.08%
Class 4: 0.00%
Class 5: 1.01%
Class 6: 0.00%
Class 7: 24.24%


# Sentence Detection

In [ ]:
data = pd.read_csv('combined_train_sentences.csv')
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scalar = StandardScaler()
X_train_scaled = scalar.fit_transform(X_train)
X_test_scaled = scalar.transform(X_test)

#svm

svm = SVC(kernel='rbf', C=100)
svm.fit(X_train_scaled, y_train)

y_pred = svm.predict(X_test_scaled)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.8094418960244648
              precision    recall  f1-score   support

           8       0.79      0.81      0.80      1749
           9       0.84      0.82      0.83      1719
          10       0.80      0.80      0.80      1764

    accuracy                           0.81      5232
   macro avg       0.81      0.81      0.81      5232
weighted avg       0.81      0.81      0.81      5232

[[1417  126  206]
 [ 164 1410  145]
 [ 205  151 1408]]


In [ ]:
# # Load data
# data = pd.read_csv('combined_train_sentences.csv')
# X = data.iloc[:, :-1]
# y = data.iloc[:, -1]

# # Split data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # Standardize features
# scalar = StandardScaler()
# X_train_scaled = scalar.fit_transform(X_train)
# X_test_scaled = scalar.transform(X_test)

# # Hyperparameter tuning using Grid Search
# param_grid = {'C': [0.1, 1, 10, 100],
#               'gamma': [1, 0.1, 0.01, 0.001],
#               'kernel': ['rbf']}

# svm_grid = GridSearchCV(SVC(), param_grid, refit=True, verbose=3)
# svm_grid.fit(X_train_scaled, y_train)

# # Print the best hyperparameters
# print("Best parameters:", svm_grid.best_params_)

# # Use the best model for prediction
# y_pred = svm_grid.predict(X_test_scaled)

# # Evaluate the model
# print("Accuracy:", accuracy_score(y_test, y_pred))
# print("Classification Report:\n", classification_report(y_test, y_pred))
# print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# # Cross-validated Accuracy
# svm_cv = SVC(kernel='rbf', C=svm_grid.best_params_['C'], gamma=svm_grid.best_params_['gamma'])
# scores = cross_val_score(svm_cv, X_train_scaled, y_train, cv=5)
# print("Cross-validated Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.340 total time= 1.0min
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.340 total time= 1.0min
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.340 total time= 1.0min
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.340 total time= 1.0min
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.340 total time=  58.2s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.612 total time=  47.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.618 total time=  49.8s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.568 total time=  49.4s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.553 total time=  50.1s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.660 total time=  50.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.610 total time=  43.1s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf;

NameError: ignored

In [ ]:
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# from sklearn.svm import SVC
# from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# # Read Data
# data = pd.read_csv('combined_train_sentences.csv')

# # Split Data
# X = data.iloc[:, :-1]
# y = data.iloc[:, -1]
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # Scale Features
# scalar = StandardScaler()
# X_train_scaled = scalar.fit_transform(X_train)
# X_test_scaled = scalar.transform(X_test)

# # Train SVM Model with Best Parameters
# best_params = {'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}
# svm = SVC(**best_params)
# svm.fit(X_train_scaled, y_train)

# # Predict and Evaluate
# y_pred = svm.predict(X_test_scaled)
# print("Accuracy:", accuracy_score(y_test, y_pred))
# print("Classification Report:\n", classification_report(y_test, y_pred))
# print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 0.8325688073394495
Classification Report:
               precision    recall  f1-score   support

           8       0.83      0.83      0.83      1749
           9       0.84      0.84      0.84      1719
          10       0.82      0.83      0.82      1764

    accuracy                           0.83      5232
   macro avg       0.83      0.83      0.83      5232
weighted avg       0.83      0.83      0.83      5232

Confusion Matrix:
 [[1449  116  184]
 [ 140 1450  129]
 [ 155  152 1457]]


In [ ]:
X_new = pd.read_csv('recorded_audio (1).csv')
X_new_scaled = scalar.transform(X_new)  # Use the same scaler from training

y_new_pred = svm.predict(X_new_scaled)  # Use the trained model (best_svm)
print("Predictions on new data:", y_new_pred)
print("Output mode of the array:", np.bincount(y_new_pred).argmax())

Predictions on new data: [ 8  8  8 10  8  8 10 10  8  8  8  8  8  8  8  8  8  8 10 10  8  8  8  8
 10  9  8  9 10 10 10 10 10 10  9  9  9  8  8  8 10 10 10 10  8  8 10 10
  8  8  8  8  8  8  8  8  8 10  8  8 10 10 10 10 10 10 10 10 10 10 10 10
 10 10  9  9  9]
Output mode of the array: 8
